import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About",
  description:
    "Ponte Trade is an ICTTM company, powered by ADAMftd. We sell research-grade trade intelligence as one-time products — reports, analysis, and risk briefs.",
};

const principles = [
  {
    title: "Output, not subscriptions",
    body: "We sell the finished intelligence — PDFs, data packs, and briefs — that you buy once. No seats, no platform to learn.",
  },
  {
    title: "Grounded, not guessed",
    body: "Reports are generated by ADAMftd and verified against multiple official sources. Where sources conflict, outliers are flagged and Monte Carlo models estimate the most likely outcome.",
  },
  {
    title: "Fast, SLA-backed delivery",
    body: "Instant downloads where possible; 24h and 48h SLAs on manual reports, with QA before anything reaches you.",
  },
];

export default function AboutPage() {
  return (
    <>
      <section className="bg-navy">
        <div className="container-px py-20 lg:py-24">
          <p className="eyebrow">About Ponte Trade</p>
          <h1 className="mt-4 max-w-3xl text-4xl font-extrabold text-white sm:text-5xl">
            Trade intelligence, sold as a product
          </h1>
          <p className="mt-5 max-w-2xl text-lg text-white/70">
            Ponte (Italian for &ldquo;bridge&rdquo;) connects buyers and sellers
            to the market intelligence they need to trade with confidence —
            delivered as reports you own, not software you rent.
          </p>
          <p className="mt-5 text-sm font-medium text-gold">
            An ICTTM company · Powered by ADAMftd
          </p>
        </div>
      </section>

      <section className="bg-white py-16 lg:py-20">
        <div className="container-px grid grid-cols-1 gap-8 md:grid-cols-3">
          {principles.map((p) => (
            <div key={p.title} className="border-t-2 border-gold pt-5">
              <h2 className="text-lg font-bold">{p.title}</h2>
              <p className="mt-2 text-sm leading-relaxed text-navy/65">{p.body}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="bg-mist py-16">
        <div className="container-px grid grid-cols-1 gap-10 lg:grid-cols-2">
          <div>
            <p className="eyebrow">Ownership &amp; engine</p>
            <h2 className="mt-3 text-2xl font-extrabold sm:text-3xl">
              Backed by ICTTM, powered by ADAMftd
            </h2>
            <p className="mt-4 text-navy/70">
              Ponte Trade is owned by the International Centre for Trade
              Transparency Limited (ICTTM), the UK group behind ADAMftd. Our
              reports are produced using ADAMftd&apos;s intelligence engine —
              7B+ verified trade records, multi-source verification, and Monte
              Carlo modelling.
            </p>
            <p className="mt-4 text-navy/70">
              <a
                href="https://adamftd.com"
                target="_blank"
                rel="noopener noreferrer"
                className="font-semibold text-gold-600 hover:underline"
              >
                Learn about ADAMftd →
              </a>
            </p>
          </div>
          <div>
            <p className="eyebrow">Why Ponte Trade exists</p>
            <h2 className="mt-3 text-2xl font-extrabold sm:text-3xl">
              A different buyer
            </h2>
            <p className="mt-4 text-navy/70">
              ADAMftd serves users who want ongoing platform access. Ponte Trade
              serves a distinct buyer — the exporter, importer, or trade body
              that needs one specific intelligence product, right now, without a
              subscription commitment. Different customers, one trusted engine.
            </p>
            <div className="mt-7">
              <Link href="/catalogue" className="btn-navy">Browse the Catalogue</Link>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
