// Generates supabase/seed.sql from the code catalogue.
// Run: node --experimental-strip-types scripts/gen-seed.ts
import { writeFileSync } from "node:fs";
import { CATEGORIES, PRODUCTS } from "../lib/catalogue.ts";

const q = (s: string | null | undefined) =>
  s == null ? "null" : `'${s.replace(/'/g, "''")}'`;

let sql = "-- AUTO-GENERATED by scripts/gen-seed.ts — do not edit by hand.\n\n";

sql += "insert into categories (slug, name, description, display_order) values\n";
sql += CATEGORIES.map(
  (c) => `  (${q(c.slug)}, ${q(c.name)}, ${q(c.description)}, ${c.order})`,
).join(",\n");
sql += "\non conflict (slug) do update set name = excluded.name, description = excluded.description, display_order = excluded.display_order;\n\n";

for (const p of PRODUCTS) {
  const cfg = p.configFields ? q(JSON.stringify(p.configFields)) : "null";
  sql += `insert into products (sku, category_id, title, slug, short_description, full_description, price_cents, currency, delivery_type, is_subscription, is_configurable, config_fields, status, featured)
values (${q(p.sku)}, (select id from categories where slug = ${q(p.categorySlug)}), ${q(p.title)}, ${q(p.slug)}, ${q(p.shortDescription)}, ${q(p.fullDescription)}, ${p.priceCents}, ${q(p.currency)}, ${q(p.deliveryType)}, ${p.isSubscription}, ${p.isConfigurable}, ${cfg}::jsonb, 'published', ${Boolean(p.featured)})
on conflict (sku) do update set title = excluded.title, price_cents = excluded.price_cents, short_description = excluded.short_description, full_description = excluded.full_description, config_fields = excluded.config_fields, status = excluded.status, featured = excluded.featured;\n\n`;
}

writeFileSync("supabase/seed.sql", sql);
console.log(`Wrote supabase/seed.sql (${CATEGORIES.length} categories, ${PRODUCTS.length} products)`);
